const projects=[
{id:'decore',cat:'brand',year:'01',title:'Décor Ghar',type:'Brand Development · Influencer Marketing · E-Commerce',desc:'Supported early-stage brand development, influencer marketing initiatives, customer/return data analysis and e-commerce performance improvement.',tags:['Brand Growth','Influencer Marketing','E-Commerce'],visual:'brand',large:true,problem:'An early-stage home décor brand needed a stronger digital presence and customer-informed growth direction.',approach:'Supported brand development, influencer initiatives and analysis of customer and return behaviour.',features:['Brand development','Influencer marketing','Customer analysis','Return analysis'],outcome:'Supported clearer decisions around brand visibility, audience engagement and e-commerce performance.'},
{id:'beyou',cat:'data',year:'02',title:'Beyou Store',type:'Sales & Customer Data Analysis',desc:'Analysed sales and customer data to uncover purchasing patterns, retention factors, churn-related behaviour and commercial opportunities.',tags:['Python','Pandas','NumPy','Matplotlib'],visual:'data',problem:'Sales performance needed to be understood through customer and historical sales behaviour.',approach:'Used Python, Pandas, NumPy and Matplotlib to transform raw business data into visualizations and actionable insights.',features:['Sales trends','Customer behaviour','Repeat customers','Customer churn','Geographic and age segments'],outcome:'Provided stakeholders with data-backed insight into customer behaviour and sales performance.'},
{id:'akbeauty',cat:'brand',year:'03',title:'AK Beauty',type:'Shopify · E-Commerce Development & Management',desc:'Developed and configured the Shopify store, managing products, pricing, collections, storefront presentation and customer experience.',tags:['Shopify','Store Management','Product Management'],visual:'brand',problem:'Create a storefront aligned with the brand’s products, positioning and customer experience.',approach:'Configured the Shopify store and managed product information, collections, pricing and presentation.',features:['Shopify setup','Product uploads','Pricing','Collections','Storefront presentation'],outcome:'Established a structured e-commerce storefront aligned with the brand direction.'},
{id:'dc',cat:'brand',year:'04',title:'DCORVO',type:'E-Commerce Brand Development',desc:'Co-founded and developed an independent consumer brand, working across product positioning, pricing, digital presence, content planning and online growth.',tags:['Brand Strategy','E-Commerce','Product Positioning'],visual:'brand',problem:'Build a consumer brand from product direction through digital selling.',approach:'Worked across product positioning, pricing, digital presence, content planning and market/customer insights.',features:['Product positioning','Pricing','Digital presence','Content planning','Online growth'],outcome:'Developed an independent brand concept with a customer-focused commercial direction.'},
{id:'shoe',cat:'brand',year:'05',title:'She Shoe Official',type:'E-Commerce Brand Development',desc:'Developed and managed an independent footwear brand concept across identity, product presentation, pricing and customer-focused online selling.',tags:['Brand Identity','E-Commerce','Footwear'],visual:'brand',problem:'Create a focused footwear brand concept and online selling experience.',approach:'Worked across brand identity, product presentation, pricing and customer-focused online selling.',features:['Brand identity','Product presentation','Pricing','Market opportunities'],outcome:'Built a coherent brand concept around product and customer preferences.'},
{id:'pak',cat:'data',year:'06',title:'Pak Metrics',type:'Pakistan Data Visualization Platform',desc:'A data-focused platform presenting Pakistan’s economic, social and government statistics through interactive visualizations, comparisons, trends and analytical insights.',tags:['Data Visualization','Public Data','Analytics'],visual:'data',large:true,problem:'Public statistics can be difficult to interpret across multiple sources and time periods.',approach:'Transformed complex statistical datasets into clear charts, comparisons and visual insights.',features:['Economic statistics','Social statistics','Government data','Comparisons','Trend analysis'],outcome:'Designed to make public data more accessible and useful for research, analysis and informed decision-making.'},
{id:'analytics',cat:'data',year:'07',title:'E-Commerce Intelligence Platform',type:'Data Analytics · Business Intelligence',desc:'A web-based analytics concept that transforms raw e-commerce data into KPIs, charts, performance summaries, business insights and predictive outputs.',tags:['Python','Data Analysis','Business Intelligence'],visual:'data',problem:'Raw e-commerce exports can contain useful signals but require cleaning, analysis and visualization.',approach:'Connect revenue, profit, cost, product performance, customer behaviour and forecasts in one decision-support interface.',features:['CSV analysis','KPIs','Charts','Customer insights','Predictive outputs'],outcome:'A structured concept for turning e-commerce data into understandable decision support.'},
{id:'pharmacy',cat:'software',year:'08',title:'Pharmacy Management System',type:'Business Software · POS · Inventory',desc:'Business software concept covering product management, inventory, billing, sales, reports, search and user roles.',tags:['Python','SQLite','POS'],visual:'software',problem:'Pharmacy workflows require reliable product, inventory and billing operations.',approach:'Designed practical business software around product, sales, inventory and reporting workflows.',features:['Products','Inventory','Billing','Sales','Reports','Search','User roles'],outcome:'A practical business-system architecture focused on day-to-day pharmacy operations.'},
{id:'retail',cat:'software',year:'09',title:'Retail Store POS',type:'POS · Inventory · Sales Analytics',desc:'Retail software covering product management, fast product search, sales, inventory, customer data and reporting.',tags:['Python','POS','Reporting'],visual:'software',problem:'Retail staff need fast product search and reliable transaction workflows.',approach:'Designed a streamlined POS flow connecting products, sales, inventory and reports.',features:['Fast search','Products','Sales','Inventory','Customer data','Reports'],outcome:'A business-focused POS architecture for retail workflows.'},
{id:'school',cat:'software',year:'10',title:'School Management System',type:'Education Software · ERP',desc:'Education software architecture covering students, sessions, classes, fees, staff, reports and results.',tags:['ERP','Python','Database'],visual:'software',problem:'Schools need structured administration across students, sessions, classes and fees.',approach:'Designed modular workflows for student management, fee management, sessions, staff and reporting.',features:['Students','Sessions','Classes','Fees','Staff','Reports','Results'],outcome:'A structured school ERP concept built around real administrative workflows.'},
{id:'lab',cat:'software',year:'11',title:'Laboratory Management System',type:'Lab ERP · Business Software',desc:'Lab workflow covering test management, sales, profit dashboards, customer reporting and role-based operations.',tags:['Python','Flask','SQLite'],visual:'software',problem:'Laboratory operations require connected test, sales and reporting workflows.',approach:'Designed modules for tests, sales, customer reporting, dashboards and roles.',features:['Test management','Sales','Profit dashboard','Customer reports','Roles'],outcome:'A practical Lab ERP concept focused on operational visibility.'}
];
const grid=document.querySelector('#projects');
function render(filter='all'){grid.innerHTML=projects.filter(p=>filter==='all'||p.cat===filter).map(p=>`<article class="project ${p.large?'large':''} reveal visible" data-id="${p.id}" data-cat="${p.cat}"><div class="project-meta"><span>${p.year} / ${p.cat.toUpperCase()}</span><span>EXPLORE ↗</span></div><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="visual ${p.visual}">${p.visual==='software'?'<div class="mini-box"></div><div class="mini-line"></div>':p.visual==='data'?'<div class="mini-line"></div>':''}</div></article>`).join('');grid.querySelectorAll('.project').forEach(card=>card.addEventListener('click',()=>openProject(card.dataset.id)));}
render();
document.querySelectorAll('.filter button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)}));
const modal=document.querySelector('#modal'),modalContent=document.querySelector('#modalContent');
function openProject(id){const p=projects.find(x=>x.id===id);modalContent.innerHTML=`<div class="section-kicker">${p.year} / ${p.type}</div><h2>${p.title}</h2><p>${p.desc}</p><div class="modal-grid"><div class="modal-box"><h4>Problem</h4><p>${p.problem}</p></div><div class="modal-box"><h4>Approach</h4><p>${p.approach}</p></div><div class="modal-box"><h4>Key Features</h4><p>${p.features.join(' · ')}</p></div><div class="modal-box"><h4>Outcome / Contribution</h4><p>${p.outcome}</p></div></div><div class="tag-row">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>`;modal.classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');document.body.style.overflow=''}document.querySelector('.close').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const nav=document.querySelector('#nav');window.addEventListener('scroll',()=>{nav.classList.toggle('scrolled',scrollY>30);document.querySelector('.progress').style.width=`${scrollY/(document.body.scrollHeight-innerHeight)*100}%`},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));
const menu=document.querySelector('.mobile-menu');document.querySelector('.menu-btn').onclick=()=>menu.classList.toggle('open');menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));
const copy=document.querySelector('#copyEmail');copy.onclick=async()=>{try{await navigator.clipboard.writeText('arslanshah293@outlook.com');copy.innerHTML='Copied ✓';setTimeout(()=>copy.innerHTML='Copy Email <b>↗</b>',1600)}catch{copy.innerHTML='arslanshah293@outlook.com'}};
const cursor=document.querySelector('.cursor');window.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});document.addEventListener('mouseover',e=>{if(e.target.closest('a,button,.project,.discipline,.skill-cloud span'))cursor.classList.add('view');else cursor.classList.remove('view')});
